FROM ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/fastdeploy-cuda-12.6:tag-base
ARG PADDLE_VERSION=3.3.1
ARG FD_VERSION=2.5.0

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workspace

RUN echo "ulimit -u unlimited" >> /root/.bashrc
RUN echo "ulimit -n 65536" >> /root/.bashrc

# uninstall existing package
RUN python -m pip uninstall paddlepaddle-gpu fastdeploy-gpu -y

# install paddlepaddle
RUN python -m pip install --no-cache-dir paddlepaddle-gpu==${PADDLE_VERSION} -i https://www.paddlepaddle.org.cn/packages/stable/cu126/

# build and install FastDeploy
RUN python -m pip install --no-cache-dir  fastdeploy-gpu==${FD_VERSION} -i https://www.paddlepaddle.org.cn/packages/stable/cu126/ --extra-index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

# install fd-router
ARG fd_router_url=https://paddle-qa.bj.bcebos.com/paddle-pipeline/FastDeploy_ActionCE/v2.5.0/latest/fd-router
RUN wget -q --no-proxy ${fd_router_url} -O /usr/local/bin/fd-router
RUN chmod +x /usr/local/bin/fd-router

ENV http_proxy=""
ENV https_proxy=""
ENV no_proxy=""
